default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 12345678
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: task-manager-api_development

test:
  <<: *default
  database: task-manager-api_test

production:
  <<: *default
  database: task-manager-api_production
  username: task-manager-api
  password: <%= ENV['TASK-MANAGER-API_DATABASE_PASSWORD'] %>
